#!/bin/sh

### BEGIN INIT INFO
# Provides:         monaggre-smtpd
# Required-Start:   $network $remote_fs
# Required-Stop:    $network $remote_fs
# Default-Start:    2 3 4 5
# Default-Stop:     0 1 6
### END INIT INFO

NAME=monaggre-smtpd
MONAGGRE_DIR=/opt/monaggre
MONAGGRE=$MONAGGRE_DIR/monaggre.py
MONAGGRE_CONFIG=$MONAGGRE_DIR/monaggre-smtpd.conf
MONAGGRE_PIDFILE=/run/lock/monaggre-smtpd.pid

if [ -f /etc/default/$NAME ] ; then
    . /etc/default/$NAME
fi

case "$1" in
    start)
        python $MONAGGRE smtpd $MONAGGRE_CONFIG
        ;;
    stop)
        kill `cat $MONAGGRE_PIDFILE`
        ;;
    restart)
        $0 stop && sleep 2 && $0 start
        ;;
    *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|restart}" >&2
        exit 1
        ;;
esac

exit 0;
